# Generated by Django 4.2 on 2023-05-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhtsensordata',
            options={'verbose_name': 'DHT Sensor Data', 'verbose_name_plural': 'DHT Sensor Data'},
        ),
    ]
