# Generated by Django 4.2 on 2023-05-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_unit_on', models.BooleanField()),
            ],
            options={
                'db_table': 'app_state',
            },
        ),
    ]
