# Generated by Django 4.2 on 2023-05-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ac_ctl', '0001_initial'),
        ('remote_web', '0003_delete_dhtsensordata'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DhtSensorData',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True,
                                                   primary_key=True,
                                                   serialize=False,
                                                   verbose_name='ID')),
                        ('date', models.DateTimeField()),
                        ('temp_c', models.FloatField()),
                        ('humidity', models.FloatField()),
                    ],
                    options={
                        'verbose_name': 'DHT Sensor Data',
                        'verbose_name_plural': 'DHT Sensor Data',
                    },
                ),
            ],
            # Table already exists, See
            # remote_web/migrations/0003_delete_dhtsensordata.py
            database_operations=[],
        )
    ]
