# Generated by Django 4.2 on 2023-05-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_web', '0002_alter_dhtsensordata_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='DhtSensorData',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='DhtSensorData',
                    table='ac_ctl_dhtsensordata'
                )
            ]
        )
    ]
