name: Django CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  django:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup envrionment
      run: |
        echo "${{secrets.DJANGO_ENV}}" >> ac_ctl_web/env.py
    - name: Run Tests
      run: |
        python manage.py test
