name: Django CI (Homeserver)

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/django-homeserver.yml'
      - 'homeserver/ac_ctl_web/**'
      - 'homeserver/backend/**'
      - 'homeserver/services/**'
      - 'homeserver/utilities/**'
      - 'homeserver/manage.py'
      - 'homeserver/Pipfile'
      - 'homeserver/Pipfile.lock'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/django-homeserver.yml'
      - 'homeserver/ac_ctl_web/**'
      - 'homeserver/backend/**'
      - 'homeserver/services/**'
      - 'homeserver/utilities/**'
      - 'homeserver/manage.py'
      - 'homeserver/Pipfile'
      - 'homeserver/Pipfile.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  work-dir: ./homeserver

defaults:
  run:
    working-directory: ./homeserver

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pipenv'
      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv wheel
      - run: pipenv install --deploy --dev
      - name: Setup environment
        run: |
          echo "$DJANGO_ENV" >> ac_ctl_web/env.py
        env:
          DJANGO_ENV: ${{secrets.DJANGO_ENV}}
      - name: Run Tests
        run: |
          pipenv run python manage.py test
      - name: Check migrations
        run: |
          pipenv run python manage.py makemigrations --check
          pipenv run python manage.py migrate
          
