name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  django:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install Dependencies
      run: |
        pipenv install --deploy --dev
    - name: Setup envrionment
      run: |
        echo "$DJANGO_ENV" >> ac_ctl_web/env.py
      env:
        DJANGO_ENV: ${{secrets.DJANGO_ENV}}
    - name: Run Tests
      run: |
        pipenv run python manage.py test
