name: Python Linter

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'requirements.txt'
      - 'package.json'
      - 'package-lock.json'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Analysing the code with flake8
        if: always()
        run: |
          flake8
