# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI (Homeserver)

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/react.yml'
      - 'frontend/**'
      - 'package.json'
      - 'yarn.lock'
      - 'webpack.config.js'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/react.yml'
      - 'frontend/**'
      - 'package.json'
      - 'yarn.lock'
      - 'webpack.config.js'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  work-dir: ./homeserver

defaults:
  run:
    working-directory: ./homeserver/frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: ./homeserver/yarn.lock
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/{1}', env.work-dir, '**/package-lock.json'), format('{0}/{1}', env.work-dir, '**/yarn.lock')) }}-${{ hashFiles(format('{0}/{1}', env.work-dir, '**.[jt]s'), format('{0}/{1}', env.work-dir, '**.[jt]sx')) }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles(format('{0}/{1}', env.work-dir, '**/package-lock.json'), format('{0}/{1}', env.work-dir, '**/yarn.lock')) }}-
      - name: Install dependencies
        run: yarn install
      - run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: remote-ac-controller-webpack
          path: |
            frontend/static/
            webpack-stats.json
    # - run: yarn test
